apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-service
  template:
    metadata:
      labels:
        app: express-service
    spec:
      containers:
      - name: express-service
        image: express-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: FLASK_SERVICE_HOST
          value: "flask-service"
        - name: FLASK_SERVICE_PORT
          value: "5000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
